name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          ./run.sh

      - name: Send slack notification on failure
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          BRANCH: ${{ github.ref }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        if: failure()
        run: |
          ./send_slack_notificaton.sh $WEBHOOK_URL $REPOSITORY $BRANCH $RUN_ID "Failed"

      - name: Send slack notification on success
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          BRANCH: ${{ github.ref }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        if: success()
        run: |
          ./send_slack_notificaton.sh $WEBHOOK_URL $REPOSITORY $BRANCH $RUN_ID "Success"
