name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          exit 1 # sumulate a failure

      - name: Send slack notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          BRANCH: ${{ github.ref }}
          REPOSITORY: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        if: failure()
        run: |
          MESSAGE="
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":red_circle: *GitHub Workflow Failed*"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${REPOSITORY}"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${BRANCH}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<https://github.com/${REPOSITORY}/actions/runs/${RUN_ID}|View Details>"
                }
              }
            ]
          }
          "
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" $WEBHOOK_URL
