name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo "Running tests..."
          exit 1 # sumulate a failure

      - name: Send slack notification
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          MESSAGE: "{ 'text': 'GitHub workflow failed. <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>' }"
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' --data "$MESSAGE" $WEBHOOK_URL
